<a href="https://colab.research.google.com/github/everestso/Fall2021/blob/main/c165MLP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
data = [((0,0),0), ((0,1),1), ((1,0),1), ((1,1),0)]


In [2]:
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPClassifier, MLPRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
import numpy as np

In [70]:
clf = MLPClassifier(
                activation='logistic',
                max_iter=10000000,
                hidden_layer_sizes=(2,),
                solver='lbfgs')
X= [x for x,y in data]
Y= [y for x,y in data]
print (X)
print (Y)
clf.fit(X,Y)
Predict = clf.predict(X)
PredictProb = clf.predict_proba(X)
print(Predict)
print(PredictProb)
print(clf.coefs_)
print(clf.intercepts_)

[(0, 0), (0, 1), (1, 0), (1, 1)]
[0, 1, 1, 0]
[0 0 1 1]
[[0.99858771 0.00141229]
 [0.50045966 0.49954034]
 [0.00129603 0.99870397]
 [0.49954033 0.50045967]]
[array([[ 4.62245227, -4.92232147],
       [10.15044136, 10.1073792 ]]), array([[ 8.05523709],
       [-8.38499766]])]
[array([-1.7686401 ,  3.22574771]), array([0.32975254])]


In [71]:
Predict = clf.predict(X)
PredictProb = clf.predict_proba(X)
print(Predict)
print(PredictProb)

[0 0 1 1]
[[0.99858771 0.00141229]
 [0.50045966 0.49954034]
 [0.00129603 0.99870397]
 [0.49954033 0.50045967]]


Network <div style="text-align: left;"><img src="https://raw.githubusercontent.com/everestso/Fall2021/main/FeedForwardNetwork2Units.png" width="400" height="400" /></div> Network

Network <img src="https://raw.githubusercontent.com/everestso/Fall2021/main/FeedForwardNetwork2Units.png" width="400" height="400" alt="Sunflower" style="float: left; margin-left: 15px;"> Network

In [79]:
# W1
W1 = clf.coefs_[0][:,0]
W1=np.insert(W1, 0, clf.intercepts_[0][0])
print("W1=", W1)

# W2
W2 = clf.coefs_[0][:,1]
W2=np.insert(W2, 0, clf.intercepts_[0][1])
print("W2=", W2)

# V1
V1 = clf.coefs_[1][:,0]
V1 = np.insert(V1, 0, clf.intercepts_[1][0])
print ("V1=", V1)

W1= [-1.7686401   4.62245227 10.15044136]
W2= [ 3.22574771 -4.92232147 10.1073792 ]
V1= [ 0.32975254  8.05523709 -8.38499766]


In [73]:
F = lambda m, x: m[0] + m[1]*x[0] + m[2]*x[1]
G = lambda y: 1/(1+np.exp(-y))

In [77]:
X=(1,0)
Z1 = G(F(W1, X))
Z2 = G(F(W2, X))
Y1 = G(F(V1, (Z1, Z2)))
print(Y1)

0.9987039740622372


In [75]:
Ynet1 = lambda wa, wb, v, x: G( F( v, (G(F(wa, x)), G(F(wb, x)))))

In [78]:
print(Ynet1(W1, W2, V1, X))
P1 = [b for a,b in PredictProb ]
P2 = [Ynet1(W1, W2, V1, x) for x,y in data]
print(P1)
print(P2)

0.9987039740622372
[0.0014122913888897541, 0.4995403387570756, 0.9987039740622372, 0.5004596693293114]
[0.0014122913888897528, 0.4995403387570756, 0.9987039740622372, 0.5004596693293113]
